version: '3.8'

services:



    onlinetravel:
        build: OnlineTravel_Sprint1
        ports:
        - 8022:8022



    postgres:
        image: postgres:14.5
        ports:
        - 5432:5432

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pgadmin
            POSTGRES_DB: traveluserdb
